"""remove_users_table

Revision ID: 4d985d9f9f1f
Revises: 001
Create Date: 2025-12-16 00:32:51.643801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d985d9f9f1f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_email_active'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment="User's email address (unique)"),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment="User's full name"),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the user account is active'),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Whether the user has superuser privileges'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_email_active'), 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###
