"""batch_3_social_interactions

Revision ID: 8cc1d6356283
Revises: d1a9acb94a0f
Create Date: 2025-12-16 00:53:01.057476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc1d6356283'
down_revision: Union[str, None] = 'd1a9acb94a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
